--returns current date and time
Select GETDATE() AS TODAY_DATE;
Select SYSDATETIME() AS TODAY_DATE;
Select CURRENT_TIMESTAMP AS TODAY_DATE;

SELECT DATENAME(MONTH, CURRENT_TIMESTAMP) AS 'Current Month';
SELECT DATENAME(YEAR, CURRENT_TIMESTAMP) AS 'Current Year';
SELECT DATENAME(HOUR, CURRENT_TIMESTAMP) AS 'Current Hour';

SELECT DATEDIFF(YEAR, 'MAY 26 2001', CURRENT_TIMESTAMP) AS "AgeInYears";
SELECT DATEDIFF(MONTH, 'MAY 26 2001', CURRENT_TIMESTAMP) AS "AgeInMonths";
SELECT DATEDIFF(YEAR, 'MAY 26 2001', 'MAY 26 2025') AS "AgeInYears";

SELECT DATEADD(YEAR, 50, CURRENT_TIMESTAMP) AS 'After 50 years';

select * from employee_info;

