CREATE FUNCTION getAllEmployeesById(@dId AS INT)
RETURNS @Table TABLE
(ID INT, NAME VARCHAR(50), SALARY DECIMAL(10,2),  JOB VARCHAR(30), PHONENO VARCHAR(10),  DEPTID INT, JDATE DATE)
AS 
	BEGIN 
		INSERT INTO @Table
		SELECT * FROM employee_info WHERE deptId = @dId;
		RETURN
	END;	

SELECT * FROM dbo.getAllEmployeesById(30);